import { render } from "@testing-library/react";
import { vi } from "vitest";
import { Phase2App, type Phase2AppServices } from "../Phase2App";
import type { RunDto, RunEvent, RuntimeEnvironment, Unlisten } from "../phase2";
export const deferred = <T,>() => { let resolve!: (v: T) => void; let reject!: (e: unknown) => void; const promise = new Promise<T>((a, b) => { resolve = a; reject = b; }); return { promise, resolve, reject }; };
export const createRunDto = (overrides: Partial<RunDto> = {}): RunDto => ({ id: "run-a", task_text: "task", agent_kind: "fake", status: "running", schema_version: 1, created_at_ms: 1, started_at_ms: null, finished_at_ms: null, exit_code: null, error_category: null, error_message: null, cancellable: overrides.cancellable ?? !["cancelled", "completed", "failed"].includes(overrides.status ?? "running"), ...overrides });
export const createRunEvent = (overrides: Partial<RunEvent> = {}): RunEvent => ({ schema_version: 1, run_id: "run-a", sequence_number: 1, event_type: "message", timestamp_ms: 1, payload: { type: "message", text: "hello" }, ...overrides });
export const createRuntimeEnvironment = (overrides: Partial<RuntimeEnvironment> = {}): RuntimeEnvironment => ({ schema_version: 1, database_initialized: true, fake_agent_available: true, ...overrides });
export function createMockPhase2Services() { let callback: ((event: RunEvent) => void) | undefined; let focusCallback: (() => void) | undefined; let activeRunListeners = 0; let runRegistrations = 0; let activeFocusListeners = 0; let focusRegistrations = 0; let runGate: Promise<void> | undefined; let focusGate: Promise<void> | undefined; let runFailure: unknown; let focusFailure: unknown; const unlisten = vi.fn(); const focusUnlisten = vi.fn(); const api = { environment: vi.fn().mockResolvedValue(createRuntimeEnvironment()), listRuns: vi.fn().mockResolvedValue([]), getRun: vi.fn().mockResolvedValue(createRunDto()), listRunEvents: vi.fn().mockResolvedValue([]), submitFakeRun: vi.fn().mockResolvedValue(createRunDto()), cancelRun: vi.fn().mockResolvedValue("cancellation_requested") } as unknown as Phase2AppServices["api"]; const services: Phase2AppServices = { api, listenToRunEvents: vi.fn().mockImplementation(async (next) => { if (runGate) await runGate; if (runFailure) throw runFailure; callback = next; activeRunListeners += 1; runRegistrations += 1; let cleaned = false; return () => { if (!cleaned) { cleaned = true; activeRunListeners -= 1; unlisten(); } }; }), listenToTaskInputFocus: vi.fn().mockImplementation(async (next) => { if (focusGate) await focusGate; if (focusFailure) throw focusFailure; focusCallback = next; activeFocusListeners += 1; focusRegistrations += 1; let cleaned = false; return () => { if (!cleaned) { cleaned = true; activeFocusListeners -= 1; focusUnlisten(); } }; }), hidePrompt: vi.fn().mockResolvedValue(undefined) }; return { services, api, unlisten, focusUnlisten, emit: (event: RunEvent) => callback?.(event), emitFocus: () => focusCallback?.(), activeRunListeners: () => activeRunListeners, runRegistrations: () => runRegistrations, activeFocusListeners: () => activeFocusListeners, focusRegistrations: () => focusRegistrations, delayRunRegistration: () => { const gate = deferred<void>(); runGate = gate.promise; return gate; }, rejectRunRegistration: (error = new Error("run registration failed")) => { runFailure = error; }, delayFocusRegistration: () => { const gate = deferred<void>(); focusGate = gate.promise; return gate; }, rejectFocusRegistration: (error = new Error("focus registration failed")) => { focusFailure = error; } }; }
export const renderPhase2App = (services = createMockPhase2Services().services) => render(<Phase2App services={services} />);
