import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { V3TaskDetail } from "./V3TaskDetail";
import type { V3Detail } from "./V3Workflow";

const detail = (overrides: Partial<V3Detail> = {}): V3Detail => ({ task: { id: "task", summary: "Ship detail", lifecycle: "ready_for_human", recoveryRequired: false }, activity: [{ kind: "validation_reported", provider: "codex", occurredAtMs: 1 }], worktree: { repositoryRoot: "/repo", path: "/worktree", branch: "agent/task", baseCommit: "base", state: "ready" }, diff: { filesChanged: 2 }, validations: [{ id: "check", profile: "test", check: "unit", state: "failed", summary: "exit 1" }], findings: [{ id: "finding", severity: "blocker", disposition: "confirmed_blocking", summary: "Fix me", evidence: { file: "src/a.rs", line: 3 } }], repairRounds: [{ id: "round", round: 1, state: "completed", updatedAtMs: 2 }], finalApprovalPacket: { unresolved_risks: ["risk"] }, finalApprovalId: "approval", agent: "claude", ...overrides });
describe("V3TaskDetail", () => {
  it("renders healthy hierarchy, deterministic validation, blockers, repair, and approval actions", async () => { const approve = vi.fn(); const stop = vi.fn(); render(<V3TaskDetail detail={detail()} state="ready-for-review" busy={false} onStop={stop} onDecision={approve} />); expect(screen.getByText("Ship detail")).toBeInTheDocument(); expect(screen.getByText("Claude · ready_for_human")).toBeInTheDocument(); expect(screen.getByText("test / unit")).toBeInTheDocument(); expect(screen.getByText("1 blocker")).toBeInTheDocument(); expect(screen.getByText("Round 1")).toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Approve" })); expect(approve).toHaveBeenCalledWith(true); });
  it("keeps recovery and conditional actions explicit", () => { render(<V3TaskDetail detail={detail({ task: { id: "task", summary: "Recover", lifecycle: "recovering", recoveryRequired: true, recoveryReason: "session_recovery_required" }, finalApprovalId: null })} state="recovery-required" busy={false} onStop={vi.fn()} onDecision={vi.fn()} />); expect(screen.getByRole("alert")).toHaveTextContent("Recovery required"); expect(screen.queryByRole("button", { name: "Approve" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Stop" })).not.toBeInTheDocument(); });
});
